// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEp5pC0ep4ES3FLJtGm-vF8a6ZBwZLfyU',
    appId: '1:290299394725:web:2b87493fc1bfbf96622b4c',
    messagingSenderId: '290299394725',
    projectId: 'waste-not-d02f6',
    authDomain: 'waste-not-d02f6.firebaseapp.com',
    storageBucket: 'waste-not-d02f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0gb9XFGRix4575lLJvv-NdSYtBCQB5Ig',
    appId: '1:290299394725:android:cc207bb0909cd430622b4c',
    messagingSenderId: '290299394725',
    projectId: 'waste-not-d02f6',
    storageBucket: 'waste-not-d02f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApaGI1Eq_1IKpoUYgf70H4HPJpNkGEWFI',
    appId: '1:290299394725:ios:243388777eded2de622b4c',
    messagingSenderId: '290299394725',
    projectId: 'waste-not-d02f6',
    storageBucket: 'waste-not-d02f6.appspot.com',
    androidClientId: '290299394725-c46veuc7p3lstsssb8cgnv0tri9kpoie.apps.googleusercontent.com',
    iosClientId: '290299394725-epou9u7bhvbojv5pl76nu481eivflkjp.apps.googleusercontent.com',
    iosBundleId: 'com.example.wasteNot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApaGI1Eq_1IKpoUYgf70H4HPJpNkGEWFI',
    appId: '1:290299394725:ios:243388777eded2de622b4c',
    messagingSenderId: '290299394725',
    projectId: 'waste-not-d02f6',
    storageBucket: 'waste-not-d02f6.appspot.com',
    androidClientId: '290299394725-c46veuc7p3lstsssb8cgnv0tri9kpoie.apps.googleusercontent.com',
    iosClientId: '290299394725-epou9u7bhvbojv5pl76nu481eivflkjp.apps.googleusercontent.com',
    iosBundleId: 'com.example.wasteNot',
  );
}
